import mongoose, { type Model, Schema } from 'mongoose';

// Config
import { defaultRole, roles } from '@config/index';

// Constants
import { commonVariables } from '@constants';

// Enums
import { TwoFactorMethod, UserStatus } from '@enums';

// Custom types
import type { IRecoveryCode, IStudent } from '@customTypes';

// Manage token object in db
const addressSchema = new Schema(
  {
    ascii: String,
    hex: String,
    base32: String,
    otpauth_url: String,
  },
  { _id: false },
);

const recoveryCodeSchema = new Schema<IRecoveryCode>({
  code: { type: String, required: true },
  used: { type: Boolean, default: false },
});

// Schema for StudentId
const studentIdSchema = new Schema(
  {
    formatted: {
      type: String,
      required: true,
      unique: true,
    },
    autoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  { _id: false },
);

const studentSchema = new Schema<IStudent>(
  {
    studentId: studentIdSchema, // Add studentId schema
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
    },
    gender: {
      type: String,
      enum: ['Male', 'Female', 'Other'],
      required: true,
    },
    dob: {
      type: Date,
      required: true,
    },
    role: {
      type: Number,
      enum: roles,
      default: defaultRole,
    },
    phoneNumber: {
      type: String,
      default: null,
    },
    status: {
      type: Number,
      default: UserStatus.Inactive,
    },
    googleId: String,
    facebookId: String,
    resetPasswordToken: String,
    resetPasswordExpire: Date,
    isDeleted: {
      type: Boolean,
      default: false,
    },
    twoFAOtp: {
      type: String,
      default: null,
    },
    isTwoAuthEnabled: {
      type: Boolean,
      default: false,
    },
    appToken: addressSchema,
    preferredTwoFAMethods: {
      type: [{ methodType: { type: String, enum: Object.values(TwoFactorMethod) } }],
      default: [{ methodType: TwoFactorMethod.NONE }], // Default to 'none' if no method is selected
    },
    recoveryCodes: { type: [recoveryCodeSchema], default: [] },
  },
  {
    timestamps: true,
  },
);

// Customize JSON transformation to exclude sensitive data
studentSchema.set('toJSON', {
  transform: (_doc, ret) => {
    ret.id = ret._id; // Add id
    commonVariables.USER_SENSITIVE_INFO_DB_COLUMNS.forEach((field) => delete ret[field]);
    return ret;
  },
});

export const Student: Model<IStudent> = mongoose.model<IStudent>('student', studentSchema);

// Function to format the user document
export const studentModelToDomain = (StudentDoc: IStudent) => {
  const formattedDoc = {
    id: StudentDoc.id.toString(),
    email: StudentDoc.email,
    name: StudentDoc.name,
    role: StudentDoc.role,
    status: StudentDoc.status === null ? undefined : StudentDoc.status,
    isDeleted: StudentDoc.isDeleted === null ? undefined : StudentDoc.isDeleted,
    isTwoAuthEnabled: StudentDoc.isTwoAuthEnabled === null ? undefined : StudentDoc.isTwoAuthEnabled,
    createdAt: StudentDoc.createdAt === null ? undefined : StudentDoc.createdAt,
    updatedAt: StudentDoc.updatedAt === null ? undefined : StudentDoc.updatedAt,
  };
  // Optionally, you can also sanitize any nested objects or arrays if needed
  return formattedDoc;
};
